{% set name = 'jupyter_latex_envs' %}
{% set version = "1.4.4" %}
{% set sha256 = 'b0a83e0cda2d33e61c4b2da94365d2de4dfcdc1ed67abdba3cbe390872cf5231' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - pip
    - python
    - setuptools
  run:
    - python
    - ipython
    - jupyter_contrib_core >=0.3
    - nbconvert
    - notebook >=4.0
    - setuptools
    - traitlets >=4.1

test:
  imports:
    - latex_envs
    - latex_envs.latex_envs

about:
  summary: Jupyter nbextension providing some LaTeX environments for markdown cells.
  home: https://github.com/jfbercher/jupyter_latex_envs
  license_file: LICENSE.txt
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jcb91
    - jfbercher
