appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: K8jj0RMoOwJ5jYC+iGkh0+5buA7/64gxTbLUondb6//IuwasPsF5p25/ytcrNiI61befZ+JqW6bS2lEhxpN3SVA9u85AxbGPxcZQHV3Dwt4mGb84Q+f6qILxWfnifYvw2oeFXrNLUJXPRFRKjPAvLmEAUaNrnSWo/h2DnLF9moscXI7236H2Rox5O35ZQHWdgOHxSOj8zIpdOiEkd5JfioHiyZQw4Mt20bF55ssTtriCwOG28VKLRCvDDuESgZskFEbbQQFtNw8oq3tkfBzOhUHOF5AdZ6+NeL5zQPNO7LT4Kt4P77VUKCarXuMkdNQgMBnthqtJAGQhQxg+kz4FcMWRfbENxeVNZ6GSpxSlaK+C3MVH2CZkU/k3DV0SVDo7J0cazAlYjRD/FX6Fe7FVZN2Oncxwku7uHk+1hL7JZt4Z8XonlBw7FNybMvXqFQUO9QWeoPzPL4NENU00A+r5Wcm86t28Yv9xm3n8W3zyoJG6fHRu2kWDgrWueXXhZs7sjQ0TfUCoHu9rmTPJMRXVZWmyKRXJKxph/6x+nbYl1qECudz+c5KauOu1mdLGG/6BDw73sARW3ZqWYGTMfPotGuo0XqPkWAMvtudCxI1mNTlWu+SKEAz75ad3EyktQM0oHeqjTAWVoYLIDMv9sy2IwsAIxFw+qmOBYrLt1qSF258=}
conda_forge_output_validation: true
